# Generated by Django 5.2 on 2025-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
