# Generated by Django 5.2 on 2025-04-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0002_conference_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
